// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmxttaaayyhwymyiuiwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZteHR0YWFheXlod3lteWl1aXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MjczNzEsImV4cCI6MjA2MzMwMzM3MX0.KcT-vXWU3U9Si_rcadOVSGNpPWADzuPe-ECSaAAcx40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);